### PR TITLE
Login validation - all TODO items validated

### PR DESCRIPTION
**Pull request by matthewcaminiti**

### CODE REVIEW

**Comment by Gabetn** [comment]
### TODO

1. Redirect to **selectTask** class
2. Validate _select-task_ CSS doesn't break other pages 
3. Validate proper redirection

**BUG**
Redirecting not properly working

**Comment by bilasa** [comment]
> ### TODO
> 1. Redirect to **selectTask** class
> 2. Validate _select-task_ CSS doesn't break other pages
> 3. Validate proper redirection
> 
> **BUG**
> Redirecting not properly working

- Login redirects to SelectTask
- SelectTask CSS tags all unique, no breaking
- SelectTask redirects to all 3 landing pages

**Comment by EBruchet** [comment]
**Confirmed Changes**
- Login redirects to SelectTask page
- SelectTask CSS tags are now all unique, no longer conflicting with other pages, but may conflict with whatever changes come from the UI branch
- SelectTask redirects to all 3 landing pages (Manager, Staff, Customer)
- 'X' button at the top of SelectTask returns the user to the Login Page

**Changes Made:**
- Strict username and password equality checking using `===` in place of `==` (See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness)
- Added Bootstrap and general fix styling to the login form
- Added Bootstrap styling to the Select Task page to avoid using inline styling and remain consistent with the rest of the project
- Default page upon loading `localhost:8080` is the login page

Merge pending final review from @Gabetn

**Review by EBruchet — APPROVED** [review]

**Comment by Gabetn** [comment]
*Confirmed Changes*:
- Strict username and password equality checking using ===
- Styling
- Default page upon loading localhost:8080 is the login page

*Changes Made*:
1. Alert if invalid username
2. Alert if invalid password
3. If valid credentials, prior to redirection I reset the state to wipe the submitted credentials from the screen.
_NOTE_: In case the user selects the back button when choosing a task, it will now require them to re-enter credentials to log-in. 

Merge Pending final acceptance from @matthewcaminiti

**Review by Gabetn — APPROVED** [review]

**Pull request merged**
